#!/bin/bash

name=$1
shift

NAMESPACE="--namespace $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)"

CURL_OPTS=""
ns_set=false
getopts ":n:" opt;
  case ${opt} in
    n )
      NAMESPACE="--namespace $OPTARG"
      ns_set=true
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      ;;
  esac
if ${ns_set}; then
  shift $((OPTIND -1))
fi

if [[ $1 = "--" ]]; then
  shift
fi

svc=$(kubectl get deployers.core.projectriff.io ${NAMESPACE} ${name} -o jsonpath='{$.status.serviceName}')

curl -s ${svc} "$@"
